name: Federal ML Pipeline - Army Vehicle Predictive Maintenance

on:
  push:
    branches: [main, develop]
    paths:
      - 'projects/army-vehicle-predictive-maintenance/**'
  pull_request:
    branches: [main]
    paths:
      - 'projects/army-vehicle-predictive-maintenance/**'

env:
  PYTHON_VERSION: '3.11'
  PROJECT_PATH: projects/army-vehicle-predictive-maintenance

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy bandit
          pip install -r requirements.txt
      
      - name: Run Black formatter check
        working-directory: ${{ env.PROJECT_PATH }}
        run: black --check src/
      
      - name: Run Flake8 linter
        working-directory: ${{ env.PROJECT_PATH }}
        run: flake8 src/ --max-line-length=100 --ignore=E203,W503
      
      - name: Run MyPy type checker
        working-directory: ${{ env.PROJECT_PATH }}
        run: mypy src/ --ignore-missing-imports || true
      
      - name: Run Bandit security scanner
        working-directory: ${{ env.PROJECT_PATH }}
        run: bandit -r src/ -ll

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Run unit tests
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ${{ env.PROJECT_PATH }}/coverage.xml
          flags: unittests
          name: codecov-umbrella

  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Snyk security scan
        uses: snyk/actions/python-3.10@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=${{ env.PROJECT_PATH }}/requirements.txt
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ env.PROJECT_PATH }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  model-validation:
    name: Model Performance Validation
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate synthetic test data
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          python src/data/data_generator.py --num-vehicles 100 --days 90 --output data/test_data.csv
      
      - name: Validate model performance
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          echo "Model validation would run here with minimum performance thresholds"
          # python tests/test_model_performance.py --min-accuracy 0.80 --min-auc 0.85

  build-docker:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    needs: [unit-tests, security-scan]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          docker build -t army-vehicle-predictive-maintenance:${{ github.sha }} .
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: army-vehicle-predictive-maintenance:${{ github.sha }}
          format: 'sarif'
          output: 'docker-trivy-results.sarif'
      
      - name: Upload Docker scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'docker-trivy-results.sarif'
      
      - name: Log in to Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag army-vehicle-predictive-maintenance:${{ github.sha }} \
            ghcr.io/${{ github.repository }}/army-vehicle-maintenance:latest
          docker push ghcr.io/${{ github.repository }}/army-vehicle-maintenance:latest

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to staging environment
        run: |
          echo "Deployment to staging would happen here"
          # kubectl apply -f k8s/staging/
      
      - name: Run integration tests
        run: |
          echo "Integration tests would run here"
          # pytest tests/integration/ --env=staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to production environment
        run: |
          echo "Deployment to production would happen here"
          # kubectl apply -f k8s/production/
      
      - name: Run smoke tests
        run: |
          echo "Smoke tests would run here"
          # pytest tests/smoke/ --env=production
      
      - name: Notify deployment
        run: |
          echo "Deployment notification would be sent here"
